// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDn5K5UsQDT2fnnJaHKmK5QO0GgjUl8_o',
    appId: '1:885930927834:web:70abe7c8fc1f3daafaa7e3',
    messagingSenderId: '885930927834',
    projectId: 'smartmanager-cc10',
    authDomain: 'smartmanager-cc10.firebaseapp.com',
    storageBucket: 'smartmanager-cc10.firebasestorage.app',
    measurementId: 'G-V5C37DZTTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKHDLOdpJB9M5lZcSk__yooNZJbc0DRE',
    appId: '1:885930927834:android:0a8d99a39464dba6faa7e3',
    messagingSenderId: '885930927834',
    projectId: 'smartmanager-cc10',
    storageBucket: 'smartmanager-cc10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvuFzv3dX-Rj6J0RUr_AwR3sSDxDjFbus',
    appId: '1:885930927834:ios:66d4ce109a73d5dffaa7e3',
    messagingSenderId: '885930927834',
    projectId: 'smartmanager-cc10',
    storageBucket: 'smartmanager-cc10.firebasestorage.app',
    iosBundleId: 'com.example.smartmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvuFzv3dX-Rj6J0RUr_AwR3sSDxDjFbus',
    appId: '1:885930927834:ios:66d4ce109a73d5dffaa7e3',
    messagingSenderId: '885930927834',
    projectId: 'smartmanager-cc10',
    storageBucket: 'smartmanager-cc10.firebasestorage.app',
    iosBundleId: 'com.example.smartmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDn5K5UsQDT2fnnJaHKmK5QO0GgjUl8_o',
    appId: '1:885930927834:web:c7748a698a55cacdfaa7e3',
    messagingSenderId: '885930927834',
    projectId: 'smartmanager-cc10',
    authDomain: 'smartmanager-cc10.firebaseapp.com',
    storageBucket: 'smartmanager-cc10.firebasestorage.app',
    measurementId: 'G-Z509TNDWHZ',
  );

}